### ISSUE TITLE
Breaks Bootstrap3's Expand/Reduce button

### ISSUE THREAD

**Issue by ghost** [ptbrown/dokuwiki-plugin-emoji#10]
Bootstrap3 features a button that can expand the interface to use a more widescreen format instead of being constrained to the center, you can see it here: http://lotar.altervista.org/wiki/start#

It's the button in the most top right part of the interface that looks like four arrows.

When this plugin is installed, that button is no longer functional. This was not a problem with earlier versions of this plugin, I only noticed it happening when I upgraded this.

**Comment by ptbrown** [comment]
Cannot reproduce issue. Installed Bootstrap3 v2018-02-16 and enabled `fixedTopNavbar` and `fluidContainerBtn`. Seems okay here. Please provide more information such as DokuWiki version. Does the fluid button only break when editing a page or always?

**Comment by ghost** [comment]
Uh, well first of all I don't enable those options, and second I'm not sure if you understand the problem.

The problem is not that I can't make it go full width, the problem is I can't toggle it between full width and fixed width. I'm on the latest DokuWiki version. And it is always broken.

I'll try to keep exploring as to why it's breaking...

**Comment by ghost** [comment]
Okay I've been testing different commits of this github to see which ones work and which ones break. It seems that the commit that updates textcomplete to 1.8.4 is what breaks the button for me.

**Comment by ghost** [comment]
Okay yeah, when I update to the latest version but then put in the jquery.textcomplete.js from the commit just before that one, the button does not break.

**Comment by ptbrown** [comment]
> The problem is not that I can't make it go full width, the problem is I can't toggle it between full width and fixed width. I'm on the latest DokuWiki version. And it is always broken.

This is what I'm having difficulty reproducing. After installing the template the toggle button was not immediately available. I had to enable the mentioned settings. It functions as expected with Emoji. I need to investigate if there is another plugin or combination of plugins that Emoji is conflicting with rather than Bootstrap3 alone.

How does it work with the script.js that I pushed yesterday?

**Comment by ghost** [comment]
I had already tested the 'Ignore empty jQuery object.' commit, there was no change.

Is there a way I could possibly debug it with chrome? I tried looking at the console but it doesn't seem to trigger any events.

**Comment by ghost** [comment]
I am noticing that in the DOM Breakpoints list, NONE of the bootstrap3:(subcategory) events load afterward.

I'll try to do further testing...

**Comment by ghost** [comment]
I am having this problem with Emoji Substitution being the ONLY enabled extension, this is frustrating. I don't know how you're not replicating it. I think I'm gonna install a fresh dokuwiki on a separate server and see if I can't replicate it there.

**Comment by ghost** [comment]
Yeah, I don't know how you're not replicating this.

All I did was install dokuwiki, go to extension manager, install bootstrap3, go to configuration manger, change bootstrap3 to the theme, then after it loads it up enable `fluidContainerBtn`

Then install the Emoji Substitution.

Button breaks.

https://cryptopaste.org/VEdNgrG5 password is debug

**Comment by ghost** [comment]
You still there?

**Comment by popindavibe** [comment]
cf #12

**Comment by ptbrown** [comment]
Is this issue still occurring with the most recent push?

**Comment by popindavibe** [comment]
Don't know about others, but for me it looks good, looking at the commit it's the same missing semi-colons I mentioned that are now set properly. For me that did fix it and I haven't had any other issues with the plugin since that change.
