### ISSUE TITLE
Latest changes break dokuwiki's plugin editor, the codemirror plugin and several other functionalities

### ISSUE THREAD

**Issue by j0hannes** [ptbrown/dokuwiki-plugin-emoji#11]
When disabling it, dokuwiki works again as expected.

**Comment by ptbrown** [comment]
Confirmed not working with CodeMirror plugin. But are there multiple issues? Please describe other functions that don't work and if the problems persist when CodeMirror is disabled.

**Comment by j0hannes** [comment]
The extension manager plugin is also partly affected (menu disappeared) and I've noticed changes at other places after updating the emoji plugin to the latest version. Sorry for being vague; I don't remember exactly what else was different in search of the error, it just went back to the regular state after disabling the plugin.

**Comment by ptbrown** [comment]
I haven't noticed any problems with the Extension Manager but I'll look closer.

I also pulled an older version of Emoji and I don't think it ever worked with CodeMirror in highlighting mode.

**Comment by j0hannes** [comment]
It did for me, some time ago. I noticed that I had switched to the regular editor before, which was also broken by the latest update.

**Comment by ptbrown** [comment]
:thinking: What's your template?

**Comment by j0hannes** [comment]
I use the standard template and [codowik](https://github.com/evnix/codowik).
