### ISSUE TITLE
Autocomplete in lists

### ISSUE THREAD

**Issue by tholu** [ptbrown/dokuwiki-plugin-emoji#9]
When adding an emoji in a list and selecting from the autocomplete, e.g.:

```
  * my list item :bomb
```

It jumps to the next list item before completing the emoji, so the result is:

```
  * my list item :bomb
  *
```

instead of the expected

```
  * my list item :bomb:
```

Also, the plugin manager always mentions there is a new version, when the latest version is already installed.

**Comment by ptbrown** [comment]
Seems to be a conflict with the list editor's use of the Enter key. The editor is grabbing the key first and interrupting the autocomplete. Other methods of completing the emoji such as typing Tab or clicking on the name will complete it.

**Comment by tholu** [comment]
Thanks for the fast answer! I can confirm that Tab/Click works as expected.
